# Generated by Django 5.1 on 2024-08-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.CharField(default="F", max_length=1)),
                ("score", models.IntegerField()),
                ("max_combo", models.IntegerField()),
                ("max_possible_combo", models.IntegerField()),
                ("perfect", models.IntegerField()),
                ("great", models.IntegerField()),
                ("okay", models.IntegerField()),
                ("miss", models.IntegerField()),
            ],
        ),
    ]
